amgcl: amgcl::sparse::cuda_matrix< value_type > Class Template Reference
amgcl::sparse::cuda_matrix< value_type > Class Template Reference
Wrapper around CUSPARSE matrix in Hybrid format.
#include <level_cuda.hpp>
Public Member Functions
cuda_matrix ()
Empty constructor.
template<class spmat >
cuda_matrix (const spmat &A)
Convert sparse matrix to cuda_matrix.
void mul (float alpha, const thrust::device_vector< float > &x, float beta, thrust::device_vector< float > &y) const
Matrix-vector product.
void mul (double alpha, const thrust::device_vector< double > &x, double beta, thrust::device_vector< double > &y) const
Matrix-vector product.
unsigned size () const
Number of rows in the matrix.
unsigned nonzeros () const
Number of nonzero entries in the matrix.
Static Public Member Functions
static void cusparseCreate ()
Initialization of CUSPARSE context.
static void cusparseDestroy ()
Releases of resources used by CUSPARSE library.
Detailed Description
template<typename value_type>
class amgcl::sparse::cuda_matrix< value_type >
Wrapper around CUSPARSE matrix in Hybrid format.
Member Function Documentation
template<typename value_type> static void amgcl::sparse::cuda_matrix< value_type >::cusparseCreate () inline static
Initialization of CUSPARSE context.
This is called automatically by cuda_matrix constructor.
Referenced by amgcl::sparse::cuda_matrix< value_t >::cuda_matrix(), and amgcl::sparse::cuda_matrix< value_t >::cusparseCreate().
template<typename value_type> static void amgcl::sparse::cuda_matrix< value_type >::cusparseDestroy () inline static
Releases of resources used by CUSPARSE library.
There is probably no need to call this.
Referenced by amgcl::sparse::cuda_matrix< value_t >::cusparseDestroy().
template<typename value_type> void amgcl::sparse::cuda_matrix< value_type >::mul (float alpha, const thrust::device_vector< float > & x, float beta, thrust::device_vector< float > & y) const inline
Matrix-vector product.
template<typename value_type> void amgcl::sparse::cuda_matrix< value_type >::mul (double alpha, const thrust::device_vector< double > & x, double beta, thrust::device_vector< double > & y) const inline
Matrix-vector product.
The documentation for this class was generated from the following file:
level_cuda.hpp