amgcl: amgcl::interp::classic Class Reference
amgcl::interp::classic Class Reference
Interpolation
Direct interpolation scheme based on Stuben (1999).
#include <interp_classic.hpp>
Classes
struct params
Parameters controlling direct interpolation.
Static Public Member Functions
template<class value_t , class index_t >
static std::pair
< sparse::matrix< value_t,
index_t >, sparse::matrix
< value_t, index_t > > interp (const sparse::matrix< value_t, index_t > &A, const params &prm)
Computes prolongation operator from a system matrix.
Detailed Description
Direct interpolation scheme based on Stuben (1999).
Member Function Documentation
template<class value_t , class index_t > static std::pair< sparse::matrix<value_t, index_t>, sparse::matrix<value_t, index_t> > amgcl::interp::classic::interp (const sparse::matrix< value_t, index_t > & A, const params & prm) inline static
Computes prolongation operator from a system matrix.
Parameters
A The system matrix.
prm Parameters.
Returns
interpolation operator.
References amgcl::sparse::matrix< value_t, index_t >::col, amgcl::interp::classic::params::eps_tr, amgcl::sparse::matrix_inner_index(), amgcl::sparse::matrix_outer_index(), amgcl::sparse::matrix_rows(), amgcl::sparse::matrix_values(), amgcl::sparse::matrix< value_t, index_t >::reserve(), amgcl::sparse::matrix< value_t, index_t >::resize(), amgcl::sparse::matrix< value_t, index_t >::row, amgcl::sparse::transpose(), amgcl::interp::classic::params::trunc_int, and amgcl::sparse::matrix< value_t, index_t >::val.
The documentation for this class was generated from the following file:
amgcl/interp_classic.hpp