amgcl: Iterative solvers
Iterative solvers
List of provided iterative solvers.
Functions
template<class matrix , class vector , class precond >
std::pair< int, typename
value_type< vector >::type > amgcl::solve (const matrix &A, const vector &rhs, const precond &P, vector &x, bicg_tag prm=bicg_tag())
Stabilized BiConjugate Gradient method.
template<class matrix , class vector , class precond >
std::pair< int, typename
value_type< vector >::type > amgcl::solve (const matrix &A, const vector &rhs, const precond &P, vector &x, cg_tag prm=cg_tag())
Conjugate Gradient method.
template<class matrix , class vector , class precond >
std::pair< int, typename
value_type< vector >::type > amgcl::solve (const matrix &A, const vector &rhs, const precond &P, vector &x, gmres_tag prm=gmres_tag())
GMRES method.
template<class value_t , gpu_matrix_format Format, class precond >
std::pair< int, value_t > amgcl::solve (const sparse::cuda_matrix< value_t, Format > &A, const thrust::device_vector< value_t > &rhs, const precond &P, thrust::device_vector< value_t > &x, cg_tag prm=cg_tag())
Conjugate Gradient method for Thrust/CUSPARSE combination.
template<class value_t , gpu_matrix_format Format, class precond >
std::pair< int, value_t > amgcl::solve (const sparse::cuda_matrix< value_t, Format > &A, const thrust::device_vector< value_t > &rhs, const precond &P, thrust::device_vector< value_t > &x, bicg_tag prm=bicg_tag())
Stabilized BiConjugate Gradient method for Thrust/CUSPARSE combination.
template<class value_t , gpu_matrix_format Format, class precond >
std::pair< int, value_t > amgcl::solve (const sparse::cuda_matrix< value_t, Format > &A, const thrust::device_vector< value_t > &rhs, const precond &P, thrust::device_vector< value_t > &x, gmres_tag prm=gmres_tag())
GMRES method for Thrust/CUSPARSE combination.
Detailed Description
List of provided iterative solvers.
Function Documentation
template<class matrix , class vector , class precond > std::pair< int, typename value_type<vector>::type > amgcl::solve (const matrix & A, const vector & rhs, const precond & P, vector & x, bicg_tag prm = bicg_tag())
Stabilized BiConjugate Gradient method.
Implementation is based on Barrett (1994)
Parameters
A The system matrix.
rhs The right-hand side.
P The preconditioner. Should provide apply(rhs, x) method.
x The solution. Contains an initial approximation on input, and the approximated solution on output.
prm The control parameters.
Returns
a pair containing number of iterations made and precision achieved.
References amgcl::axpy(), amgcl::clear(), amgcl::inner_prod(), amgcl::norm(), and amgcl::residual().
template<class matrix , class vector , class precond > std::pair< int, typename value_type<vector>::type > amgcl::solve (const matrix & A, const vector & rhs, const precond & P, vector & x, cg_tag prm = cg_tag())
Conjugate Gradient method.
Implementation is based on Barrett (1994)
Parameters
A The system matrix.
rhs The right-hand side.
P The preconditioner. Should provide apply(rhs, x) method.
x The solution. Contains an initial approximation on input, and the approximated solution on output.
prm The control parameters.
Returns
a pair containing number of iterations made and precision achieved.
References amgcl::axpy(), amgcl::clear(), amgcl::inner_prod(), amgcl::norm(), and amgcl::residual().
template<class matrix , class vector , class precond > std::pair< int, typename value_type<vector>::type > amgcl::solve (const matrix & A, const vector & rhs, const precond & P, vector & x, gmres_tag prm = gmres_tag())
GMRES method.
Implementation is based on Barrett (1994)
Parameters
A The system matrix.
rhs The right-hand side.
P The preconditioner. Should provide apply(rhs, x) method.
x The solution. Contains an initial approximation on input, and the approximated solution on output.
prm The control parameters.
Returns
a pair containing number of iterations made and precision achieved.
References amgcl::axpy(), amgcl::clear(), amgcl::inner_prod(), amgcl::norm(), and amgcl::residual().
template<class value_t , gpu_matrix_format Format, class precond > std::pair< int, value_t > amgcl::solve (const sparse::cuda_matrix< value_t, Format > & A, const thrust::device_vector< value_t > & rhs, const precond & P, thrust::device_vector< value_t > & x, cg_tag prm = cg_tag())
Conjugate Gradient method for Thrust/CUSPARSE combination.
Implementation is based on Barrett (1994)
Parameters
A The system matrix.
rhs The right-hand side.
P The preconditioner. Should provide apply(rhs, x) method.
x The solution. Contains an initial approximation on input, and the approximated solution on output.
prm The control parameters.
Returns
a pair containing number of iterations made and precision achieved.
template<class value_t , gpu_matrix_format Format, class precond > std::pair< int, value_t > amgcl::solve (const sparse::cuda_matrix< value_t, Format > & A, const thrust::device_vector< value_t > & rhs, const precond & P, thrust::device_vector< value_t > & x, bicg_tag prm = bicg_tag())
Stabilized BiConjugate Gradient method for Thrust/CUSPARSE combination.
Implementation is based on Barrett (1994)
Parameters
A The system matrix.
rhs The right-hand side.
P The preconditioner. Should provide apply(rhs, x) method.
x The solution. Contains an initial approximation on input, and the approximated solution on output.
prm The control parameters.
Returns
a pair containing number of iterations made and precision achieved.
template<class value_t , gpu_matrix_format Format, class precond > std::pair< int, value_t > amgcl::solve (const sparse::cuda_matrix< value_t, Format > & A, const thrust::device_vector< value_t > & rhs, const precond & P, thrust::device_vector< value_t > & x, gmres_tag prm = gmres_tag())
GMRES method for Thrust/CUSPARSE combination.
Implementation is based on Barrett (1994)
Parameters
A The system matrix.
rhs The right-hand side.
P The preconditioner. Should provide apply(rhs, x) method.
x The solution. Contains an initial approximation on input, and the approximated solution on output.
prm The control parameters.
Returns
a pair containing number of iterations made and precision achieved.