amgcl: amgcl::sparse Namespace Reference
amgcl::sparse Namespace Reference
A set of routines to work with sparse matrices in CRS format.
Classes
class cuda_matrix
Wrapper around CUSPARSE matrix in Hybrid format.
class viennacl_matrix_adapter
Provides proxy matrix class that may be used with ViennaCL.
struct matrix_index
Type of matrix indices.
struct matrix_value
Type of matrix values.
struct matrix
Sparse matrix in CRS format.
struct matrix_map
Proxy for sparse matrix in CRS format that does not own its data.
Functions
template<class Derived >
matrix_map< typename
Derived::Scalar, typename
Derived::Index > map (const Eigen::SparseMatrixBase< Derived > &A)
Maps Eigen sparse matrix to format supported by amgcl.
template<class spmat >
viennacl_matrix_adapter< spmat > viennacl_map (const spmat &A)
template<class spmat >
matrix_index< spmat >::type matrix_rows (const spmat &A)
Number of rows in a matrix.
template<class spmat >
matrix_index< spmat >::type matrix_cols (const spmat &A)
Number of columns in a matrix.
template<class spmat >
const matrix_index< spmat >::type * matrix_outer_index (const spmat &A)
Pointer to an array of outer indices.
template<class spmat >
matrix_index< spmat >::type * matrix_outer_index (spmat &A)
Pointer to an array of outer indices.
template<class spmat >
const matrix_index< spmat >::type * matrix_inner_index (const spmat &A)
Pointer to an array of inner indices.
template<class spmat >
matrix_index< spmat >::type * matrix_inner_index (spmat &A)
Pointer to an array of inner indices.
template<class spmat >
const matrix_value< spmat >::type * matrix_values (const spmat &A)
Pointer to an array of values.
template<class spmat >
matrix_value< spmat >::type * matrix_values (spmat &A)
Pointer to an array of values.
template<class spmat >
matrix_index< spmat >::type matrix_nonzeros (const spmat &A)
Number of nonzero entries.
template<typename value_t , class index_t >
matrix_map< value_t, index_t > map (index_t rows, index_t cols, const index_t *row, const index_t *col, const value_t *val)
Constructs proxy matrix class from a raw data.
template<class spmat >
matrix< typename matrix_value
< spmat >::type, typename
matrix_index< spmat >::type > transpose (const spmat &A)
Transpose of a sparse matrix.
template<class spmat1 , class spmat2 >
matrix< typename matrix_value
< spmat1 >::type, typename
matrix_index< spmat1 >::type > prod (const spmat1 &A, const spmat2 &B)
Matrix-matrix product.
template<typename index_t , class value_t >
void gaussj (index_t n, value_t *a)
Gauss-Jordan elimination.
template<class spmat >
matrix< typename matrix_value
< spmat >::type, typename
matrix_index< spmat >::type > inverse (const spmat &A)
Inversion of a sparse matrix.
template<class spmat >
std::vector< typename
matrix_value< spmat >::type > diagonal (const spmat &A)
Returns vector containing diagonal entrix of a sparse matrix.
Detailed Description
A set of routines to work with sparse matrices in CRS format.
Function Documentation
template<class spmat > matrix< typename matrix_value<spmat>::type, typename matrix_index<spmat>::type > amgcl::sparse::inverse (const spmat & A)
Inversion of a sparse matrix.
Gauss-Jordan elimination routine is used.
References gaussj(), matrix_cols(), matrix_inner_index(), matrix_outer_index(), matrix_rows(), and matrix_values().
template<class Derived > matrix_map<typename Derived::Scalar, typename Derived::Index> amgcl::sparse::map (const Eigen::SparseMatrixBase< Derived > & A)
Maps Eigen sparse matrix to format supported by amgcl.
No data is copied here.