amgcl: amgcl::aggr Namespace Reference
amgcl::aggr Namespace Reference
Aggregation related types and functions.
Classes
struct plain
Plain aggregation.
Functions
template<class spmat >
std::vector< char > connect (const spmat &A, float eps_strong)
Strong couplings for aggregation-based AMG.
template<class spmat >
sparse::matrix< typename
sparse::matrix_value< spmat >
::type, typename
sparse::matrix_index< spmat >
::type > pointwise_matrix (const spmat &A, unsigned dof_per_node)
Builds reduced matrix for non-scalar system of equations.
template<class aggr_type , class spmat >
std::pair< std::vector< char >
, std::vector< typename
sparse::matrix_index< spmat >
::type >> pointwise_coarsening (const spmat &A, float eps_strong, unsigned dof_per_node)
Detailed Description
Aggregation related types and functions.
Function Documentation
template<class spmat > std::vector<char> amgcl::aggr::connect (const spmat & A, float eps_strong)
Strong couplings for aggregation-based AMG.
Parameters
A The system matrix
eps_strong ///< copydoc amgcl::interp::aggregation::params::eps_strong
Returns
vector of bools (actually chars) corresponding to A's nonzero entries.
References amgcl::sparse::diagonal(), amgcl::sparse::matrix_inner_index(), amgcl::sparse::matrix_nonzeros(), amgcl::sparse::matrix_outer_index(), amgcl::sparse::matrix_rows(), and amgcl::sparse::matrix_values().
Referenced by amgcl::interp::aggregation< aggr_type >::interp(), amgcl::interp::sa_emin< aggr_type >::interp(), and amgcl::interp::smoothed_aggregation< aggr_type >::interp().