amgcl: amgcl Namespace Reference
amgcl Namespace Reference
Primary namespace for the library.
Namespaces
aggr
Aggregation related types and functions.
interp
Interpolation-related types and functions.
level
Storage schemes for levels of AMG hierarchy.
relax
Possible relaxation (smoothing) schemes.
spai
Routines computing Sparse Approximate Inverses for a given matrix.
sparse
A set of routines to work with sparse matrices in CRS format.
Classes
class solver
Algebraic multigrid method.
struct cg_tag
Control parameters for Conjugate Gradient method.
struct bicg_tag
Control parameters for Stabilized BiConjugate Gradient method.
struct gmres_tag
Control parameters for GMRES method.
struct value_type< T, typename std::enable_if< std::is_arithmetic< typename T::MatrixType >::value >::type >
Returns value type of vex::vector.
struct value_type< thrust::device_vector< T > >
Returns value type for a thrust vector.
struct value_type< T, typename boost::enable_if< boost::is_arithmetic< typename T::Scalar > >::type >
Returns value type for an Eigen vector.
struct value_type< boost::numeric::ublas::vector< T > >
Returns value type for an ublas vector.
struct value_type< T, typename std::enable_if< std::is_arithmetic< typename T::value_type >::value >::type >
Returns value type of vex::vector.
class viennacl_preconditioner
Wrapper around amgcl::solver that is compatible with ViennaCL solvers.
class profiler
Simple profiler class.
Typedefs
typedef value_type< vector >::type value_t
Enumerations
enum gpu_matrix_format { GPU_MATRIX_CRS, GPU_MATRIX_ELL, GPU_MATRIX_HYB }
Possible matrix storage formats for GPGPU backends.
Functions
vector r (n)
vector p (n)
vector v (n)
vector s (n)
vector t (n)
vector rh (n)
vector ph (n)
vector sh (n)
residual (A, x, rhs, r)
for (iter=0;res > prm.tol &&iter< prm.maxiter;++iter)
vector q (n)
if (norm_of_rhs==0)
for (;(res=norm(r)/norm_of_rhs) > prm.tol &&iter< prm.maxiter;++iter)
template<typename real >
std::vector< real > chebyshev_coefficients (unsigned degree, real a, real b)
Returns negated coefficients of a Chebyshev polynomial of given degree on interval [a, b].
template<typename spmat >
sparse::matrix_value< spmat >::type spectral_radius (const spmat &A)
Estimate the spectral radius of a given matric A by application of Gershgorin theorem.
template<class spmat , class VectorX , class VectorF , class VectorY >
void residual (const spmat &A, const VectorX &x, const VectorF &f, VectorY &y)
Computes residual f - A * x and stores the result in y.
template<class spmat , class VectorX , class VectorY >
void axpy (const spmat &A, const VectorX &x, VectorY &y)
Computes y = A * x (not really an axpy, I know).
gmres_data< vector > gmres (prm.M, n)
for (int i=0;i< prm.M &&iter< prm.maxiter;++i,++iter)
gmres update (x, prm.M-1)
while (iter< prm.maxiter &&res > prm.tol)
template<class value_t , gpu_matrix_format Format, class precond >
std::pair< int, value_t > solve (const sparse::cuda_matrix< value_t, Format > &A, const thrust::device_vector< value_t > &rhs, const precond &P, thrust::device_vector< value_t > &x, cg_tag prm=cg_tag())
Conjugate Gradient method for Thrust/CUSPARSE combination.
template<class value_t , gpu_matrix_format Format, class precond >
std::pair< int, value_t > solve (const sparse::cuda_matrix< value_t, Format > &A, const thrust::device_vector< value_t > &rhs, const precond &P, thrust::device_vector< value_t > &x, bicg_tag prm=bicg_tag())
Stabilized BiConjugate Gradient method for Thrust/CUSPARSE combination.
template<typename T >
T inner_prod (const blaze::DynamicVector< T > &x, const blaze::DynamicVector< T > &y)
Returns inner product of two vex::vectors.
template<typename T >
T norm (const blaze::DynamicVector< T > &x)
Returns norm of vex::vector.
template<typename T >
void clear (blaze::DynamicVector< T > &x)
Clears (sets elements to zero) vex::vector.
template<typename T >
void clear (thrust::device_vector< T > &x)
Clears (sets elements to zero) thrust vector.
template<typename T >
T inner_prod (const thrust::device_vector< T > &x, const thrust::device_vector< T > &y)
Returns inner product of two thrust vectors.
template<typename T >
T norm (const thrust::device_vector< T > &x)
Returns norm of a thrust vector.
template<class matrix , typename real >
void residual (const matrix &A, const thrust::device_vector< real > &x, const thrust::device_vector< real > &f, thrust::device_vector< real > &y)
Specialization of residual operation for thrust types.
template<class matrix , typename real >
void axpy (const matrix &A, const thrust::device_vector< real > &x, thrust::device_vector< real > &y)
Specialization of matrix-vector product for thrust types.
template<typename T1 , typename T2 >
T1::Scalar inner_prod (const Eigen::MatrixBase< T1 > &x, const Eigen::MatrixBase< T2 > &y)
Returns inner product of two Eigen vectors.
template<typename T >
T::Scalar norm (const Eigen::MatrixBase< T > &x)
Returns norm of an Eigen vector.
template<typename T >
void clear (Eigen::MatrixBase< T > &x)
Clears (sets elements to zero) an Eigen vector.
template<typename T1 , typename T2 >
T1 inner_prod (const boost::numeric::ublas::vector< T1 > &x, const boost::numeric::ublas::vector< T2 > &y)
Returns inner product of two ublas vectors.
template<typename T >
T norm (const boost::numeric::ublas::vector< T > &x)
Returns norm of an ublas vector.
template<typename T >
void clear (boost::numeric::ublas::vector< T > &x)
Clears (sets elements to zero) an ublas vector.
template<typename real >
void residual (const boost::numeric::ublas::compressed_matrix< real, boost::numeric::ublas::row_major > &A, const boost::numeric::ublas::vector< real > &x, const boost::numeric::ublas::vector< real > &f, boost::numeric::ublas::vector< real > &y)
Specialization of residual operation for ublas types.
template<typename real >
void axpy (const boost::numeric::ublas::compressed_matrix< real, boost::numeric::ublas::row_major > &A, const boost::numeric::ublas::vector< real > &x, boost::numeric::ublas::vector< real > &y)
Specialization of matrix-vector product for ublas types.
template<typename T >
T inner_prod (const vex::vector< T > &x, const vex::vector< T > &y)
Returns inner product of two vex::vectors.
template<typename T >
T norm (const vex::vector< T > &x)
Returns norm of vex::vector.
template<typename T >
void clear (vex::vector< T > &x)
Clears (sets elements to zero) vex::vector.
template<typename T >
void clear (viennacl::vector< T > &x)
template<typename T >
T inner_prod (const viennacl::vector< T > &x, const viennacl::vector< T > &y)
template<typename T >
T norm (const viennacl::vector< T > &x)
template<class matrix , typename real >
void residual (const matrix &A, const viennacl::vector< real > &x, const viennacl::vector< real > &f, viennacl::vector< real > &y)
template<class matrix , typename real >
void axpy (const matrix &A, const viennacl::vector< real > &x, viennacl::vector< real > &y)
Specialization of matrix-vector product for ublas types.
template<class vector , class AMG >
viennacl_preconditioner
< vector, AMG > make_viennacl_precond (const AMG &amg)
Wrapper around amgcl::solver that is compatible with ViennaCL solvers.
Variables
const size_t n = x.size()
rh = r
value_t rho1 = 0
value_t rho2 = 0
value_t alpha = 0
value_t omega = 0
value_t norm_of_rhs = norm(rhs)
int iter = 0
value_t res = 2 * prm.tol
do
Detailed Description
Primary namespace for the library.
Enumeration Type Documentation
enum amgcl::gpu_matrix_format
Possible matrix storage formats for GPGPU backends.
Enumerator
GPU_MATRIX_CRS
Compressed matrix. Fastest construction, slowest operation (on a GPU). Best suited for CPU compute devices.
GPU_MATRIX_ELL
ELL format. Ideal for matrices with constant number of nonzeros per row on GPU compute devices.
GPU_MATRIX_HYB
Hybrid ELL format. Best choice for general matrices on GPU compute devices.
Function Documentation
template<class matrix , typename real > void amgcl::axpy (const matrix & A, const viennacl::vector< real > & x, viennacl::vector< real > & y)
Specialization of matrix-vector product for ublas types.
Necessary for ublas types to work with amgcl::solve() functions.
References amgcl::sparse::prod().
template<typename real > void amgcl::axpy (const boost::numeric::ublas::compressed_matrix< real, boost::numeric::ublas::row_major > & A, const boost::numeric::ublas::vector< real > & x, boost::numeric::ublas::vector< real > & y)
Specialization of matrix-vector product for ublas types.
Necessary for ublas types to work with amgcl::solve() functions.
template<typename real > std::vector<real> amgcl::chebyshev_coefficients (unsigned degree, real a, real b)
Returns negated coefficients of a Chebyshev polynomial of given degree on interval [a, b].
Note
The last coefficient (at the 0-th order term) is not included.
References amgcl::sparse::gaussj().
template<typename T > void amgcl::clear (vex::vector< T > & x)
Clears (sets elements to zero) vex::vector.
Necessary for vexcl types to work with amgcl::solve() functions.
template<typename T > void amgcl::clear (Eigen::MatrixBase< T > & x)
Clears (sets elements to zero) an Eigen vector.
Necessary for eigen types to work with amgcl::solve() functions.
template<typename T > void amgcl::clear (blaze::DynamicVector< T > & x)
Clears (sets elements to zero) vex::vector.
Necessary for blaze types to work with amgcl::solve() functions.
Referenced by solve().
template<typename T > void amgcl::clear (boost::numeric::ublas::vector< T > & x)
Clears (sets elements to zero) an ublas vector.
Necessary for ublas types to work with amgcl::solve() functions.
template<typename T > T amgcl::inner_prod (const vex::vector< T > & x, const vex::vector< T > & y)
Returns inner product of two vex::vectors.
Necessary for vexcl types to work with amgcl::solve() functions.
template<typename T1 , typename T2 > T1::Scalar amgcl::inner_prod (const Eigen::MatrixBase< T1 > & x, const Eigen::MatrixBase< T2 > & y)
Returns inner product of two Eigen vectors.
Necessary for eigen types to work with amgcl::solve() functions.
template<typename T1 , typename T2 > T1 amgcl::inner_prod (const boost::numeric::ublas::vector< T1 > & x, const boost::numeric::ublas::vector< T2 > & y)
Returns inner product of two ublas vectors.
Necessary for ublas types to work with amgcl::solve() functions.
template<typename T > T amgcl::inner_prod (const blaze::DynamicVector< T > & x, const blaze::DynamicVector< T > & y)
Returns inner product of two vex::vectors.
Necessary for blaze types to work with amgcl::solve() functions.
Referenced by norm(), and solve().
template<typename T > T amgcl::norm (const vex::vector< T > & x)
Returns norm of vex::vector.
Necessary for vexcl types to work with amgcl::solve() functions.
References inner_prod().
template<typename T > T::Scalar amgcl::norm (const Eigen::MatrixBase< T > & x)
Returns norm of an Eigen vector.
Necessary for eigen types to work with amgcl::solve() functions.
template<typename T > T amgcl::norm (const blaze::DynamicVector< T > & x)
Returns norm of vex::vector.
Necessary for blaze types to work with amgcl::solve() functions.
Referenced by solve().
template<typename T > T amgcl::norm (const boost::numeric::ublas::vector< T > & x)
Returns norm of an ublas vector.
Necessary for ublas types to work with amgcl::solve() functions.
template<typename real > void amgcl::residual (const boost::numeric::ublas::compressed_matrix< real, boost::numeric::ublas::row_major > & A, const boost::numeric::ublas::vector< real > & x, const boost::numeric::ublas::vector< real > & f, boost::numeric::ublas::vector< real > & y)
Specialization of residual operation for ublas types.
Necessary for ublas types to work with amgcl::solve() functions.
Variable Documentation
amgcl::do
Initial value:
{
        res = gmres.restart(A, rhs, P, x)