amgcl: amgcl::interp::aggregation< aggr_type > Struct Template Reference
amgcl::interp::aggregation< aggr_type > Struct Template Reference
Interpolation
Aggregation-based interpolation scheme.
#include <interp_aggr.hpp>
Classes
struct params
Parameters controlling aggregation.
Static Public Member Functions
template<class value_t , class index_t >
static std::pair
< sparse::matrix< value_t,
index_t >, sparse::matrix
< value_t, index_t > > interp (const sparse::matrix< value_t, index_t > &A, const params &prm)
Constructs coarse level by aggregation.
Detailed Description
template<class aggr_type>
struct amgcl::interp::aggregation< aggr_type >
Aggregation-based interpolation scheme.
Parameters
aggr_type Aggregation scheme.
Member Function Documentation
template<class aggr_type > template<class value_t , class index_t > static std::pair< sparse::matrix<value_t, index_t>, sparse::matrix<value_t, index_t> > amgcl::interp::aggregation< aggr_type >::interp (const sparse::matrix< value_t, index_t > & A, const params & prm) inline static
Constructs coarse level by aggregation.
Returns interpolation operator, which is enough to construct system matrix at coarser level.
Parameters
A system matrix.
prm parameters.
Returns
interpolation operator.
References amgcl::sparse::matrix< value_t, index_t >::col, amgcl::aggr::connect(), amgcl::interp::aggregation< aggr_type >::params::eps_strong, amgcl::sparse::matrix_rows(), amgcl::sparse::matrix< value_t, index_t >::resize(), amgcl::sparse::matrix< value_t, index_t >::row, amgcl::sparse::transpose(), and amgcl::sparse::matrix< value_t, index_t >::val.
The documentation for this struct was generated from the following file:
interp_aggr.hpp