amgcl: amgcl::aggr::plain Struct Reference
amgcl::aggr::plain Struct Reference
Aggregation
Plain aggregation.
#include <aggr_plain.hpp>
Static Public Member Functions
template<class spmat >
static std::vector< typename
sparse::matrix_index< spmat >
::type > aggregates (const spmat &A)
Constructs aggregates of variables.
Detailed Description
Plain aggregation.
Modification of a greedy aggregation scheme from Vanek (1996). Any nonzero matrix entry forms a connection. Variables without neighbours (resulting, e.g., from Dirichlet conditions) are excluded from aggregation process. The aggregation is completed in a single pass over variables: variables adjacent to a new aggregate are temporarily marked as beloning to this aggregate. Later they may be claimed by other aggregates; if nobody claims them, then they just stay in their initial aggregate.
Member Function Documentation
template<class spmat > static std::vector< typename sparse::matrix_index<spmat>::type > amgcl::aggr::plain::aggregates (const spmat & A) inline static
Constructs aggregates of variables.
Each entry of the return vector corresponds to a variable and contains number of an aggregate the variable belongs to. If an entry is negative, then variable does not belong to any aggregate.
Parameters
A system matrix.
Returns
a vector of aggregate numbers.
References amgcl::sparse::matrix_inner_index(), amgcl::sparse::matrix_outer_index(), amgcl::sparse::matrix_rows(), and amgcl::sparse::matrix_values().
The documentation for this struct was generated from the following file:
aggr_plain.hpp